import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';
import { Keypair } from '@stellar/stellar-sdk';
import { env } from '../config/env';
import { logger } from '../utils/logger';

export interface AuthenticatedRequest extends Request {
  user?: {
    id: string;
    wallet_address: string;
  };
}

/**
 * Middleware to verify JWT token on protected routes
 */
export function verifyToken(
  req: AuthenticatedRequest,
  res: Response,
  next: NextFunction
): void {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    res.status(401).json({ success: false, error: { message: 'Access Denied: Token Missing' } });
    return;
  }

  const token = authHeader.split(' ')[1];
  try {
    const verified = jwt.verify(token, env.JWT_SECRET) as { id: string; wallet_address: string };
    req.user = verified;
    next();
  } catch (err: any) {
    res.status(403).json({ success: false, error: { message: 'Access Denied: Invalid Token' } });
  }
}

/**
 * Crypotographically verify Stellar Freighter signature
 * @param walletAddress The G... address of the user
 * @param message The raw text that was signed
 * @param signatureHex The signature generated by Freighter (typically hex or base64)
 */
export function verifyFreighterSignature(
  walletAddress: string,
  message: string,
  signatureHex: string
): boolean {
  try {
    // If we're in mock mode, bypass actual crypto checks for ease of testing
    if (signatureHex === 'mock-signature') {
      logger.info(`Bypassed cryptographic check for developer account: ${walletAddress}`);
      return true;
    }

    const keypair = Keypair.fromPublicKey(walletAddress);
    // Convert signature from hex or base64 to Buffer
    let signatureBuffer: Buffer;
    if (/^[0-9a-fA-F]+$/.test(signatureHex)) {
      signatureBuffer = Buffer.from(signatureHex, 'hex');
    } else {
      signatureBuffer = Buffer.from(signatureHex, 'base64');
    }

    const messageBuffer = Buffer.from(message, 'utf-8');
    return keypair.verify(messageBuffer, signatureBuffer);
  } catch (error: any) {
    logger.error(`Freighter signature verification failed: ${error.message}`);
    return false;
  }
}
